all:
  children:
    teamcity_master:
      hosts:
        teamcity-master-vm:
          ansible_host: 89.169.157.236
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          ansible_python_interpreter: /usr/bin/python3

      vars:
        teamcity_distro_filepath: /home/emav/TeamCity-2025.03.3.tar.gz
        teamcity_server_domain: teamcity.torrmund.xyz

    teamcity_agents:
      hosts:
        teamcity-agent-1:
          ansible_host: 89.169.130.116


      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        ansible_python_interpreter: /usr/bin/python3

        teamcity_server_domain: teamcity.torrmund.xyz
        terraform_version: 1.11.3
        kubernetes_version: "1.30"
        helm_version: 3.17.3

        registry_sa_key_filepath: ./.yc/registry_sa_key.json
        infrastructure_sa_key_filepath: ./.yc/infrastructure_sa_key.json
        infrastructure_sa_credentials_filepath: ./.yc/infrastructure_sa_credentials
        kubeconfig_filepath: ./.kube/kube_config
        demo_app_helm_values_filepath: ./helm_values/notes_app.yaml
